### ISSUE TITLE
consider www.libraw.org

### ISSUE THREAD

**Issue by ivanooi** [gasrios/raw#1]
hi,

probably u can consider use jni or jna to link with libraw

thanks

**Comment by gasrios** [comment]
Hi, sorry, I totally missed this until now.

raw is a decoder, like libraw or dcraw, not a layer on top of another raw decoding lib.

The reason I decided to write yet another decoder from stratch was twofold: (1) all existing open source decoders derive from dcraw, and (2) trying to understand how to process TIFF based raw formats by studying dcraw is challenging, to say the least.

If you are looking for a Java adapter to libraw, raw is not your best bet. This was never a goal for this project, and adapting it in this way would be so hard, that you are probably better off doing it from scratch.
